apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyz-api-deployment
  labels:
    app: xyz-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xyz-api
  template:
    metadata:
      labels:
        app: xyz-api
    spec:
      containers:
      - name: xyz-api-container
        image: ghcr.io/eparkertamu96/xyz:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: xyz-api-service
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  #   service.beta.kubernetes.io/aws-load-balancer-ssl-cert: %%CERTIFICATE_ARN%%
  #   service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"

spec:
  selector:
    app: xyz-api
  ports:
    - name: http
      port: 80
      targetPort: 80
    # - name: https
    #   port: 443
    #   targetPort: 80
  type: LoadBalancer
